// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpxqrfcnpcajnomiwmhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweHFyZmNucGNham5vbWl3bWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDAzMjIsImV4cCI6MjA1NzcxNjMyMn0.uOreI_cA3FoTK4Nz3nYkAAk_XZmWTiQqbvJuJS0SjUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);